site_name: SCC Firewall Manager SDK
site_description: Python SDK for Cisco Security Cloud Control Firewall Manager API

theme:
  name: readthedocs

docs_dir: docs

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
    - AIAssistantApi: AIAssistantApi.md
    - ASAAccessGroupsApi: ASAAccessGroupsApi.md
    - ASAAccessRulesApi: ASAAccessRulesApi.md
    - ASAInterfacesApi: ASAInterfacesApi.md
    - AccessGroupsApi: AccessGroupsApi.md
    - AuditLogsApi: AuditLogsApi.md
    - ChangeRequestsApi: ChangeRequestsApi.md
    - ChangelogsApi: ChangelogsApi.md
    - CloudDeliveredFMCApi: CloudDeliveredFMCApi.md
    - CommandLineInterfaceApi: CommandLineInterfaceApi.md
    - CommandsApi: CommandsApi.md
    - ConnectorsApi: ConnectorsApi.md
    - DeviceHealthAggregationsApi: DeviceHealthAggregationsApi.md
    - DeviceHealthApi: DeviceHealthApi.md
    - DeviceUpgradesApi: DeviceUpgradesApi.md
    - EventsApi: EventsApi.md
    - InterfaceHealthAggregationsApi: InterfaceHealthAggregationsApi.md
    - InventoryApi: InventoryApi.md
    - LicensingApi: LicensingApi.md
    - MSPASADeviceUpgradesApi: MSPASADeviceUpgradesApi.md
    - MSPApi: MSPApi.md
    - MSPDeviceUpgradesApi: MSPDeviceUpgradesApi.md
    - MSPInventoryApi: MSPInventoryApi.md
    - MSPLicensingApi: MSPLicensingApi.md
    - MSPTenantManagementApi: MSPTenantManagementApi.md
    - MSPUserManagementApi: MSPUserManagementApi.md
    - MetaApi: MetaApi.md
    - ObjectManagementApi: ObjectManagementApi.md
    - RemoteAccessMonitoringApi: RemoteAccessMonitoringApi.md
    - SearchApi: SearchApi.md
    - SwaggerRedirectControllerApi: SwaggerRedirectControllerApi.md
    - TenantManagementApi: TenantManagementApi.md
    - TransactionsApi: TransactionsApi.md
    - UsersApi: UsersApi.md
  - Models:
    - AccessGroup: AccessGroup.md
    - AccessGroupCreateInput: AccessGroupCreateInput.md
    - AccessGroupPage: AccessGroupPage.md
    - AccessGroupUpdateInput: AccessGroupUpdateInput.md
    - AccessRule: AccessRule.md
    - AccessRuleCreateInput: AccessRuleCreateInput.md
    - AccessRuleDetailsContent: AccessRuleDetailsContent.md
    - AccessRuleIssue: AccessRuleIssue.md
    - AccessRulePage: AccessRulePage.md
    - AccessRuleUpdateInput: AccessRuleUpdateInput.md
    - ActiveDirectoryGroup: ActiveDirectoryGroup.md
    - ActiveDirectoryGroupCreateOrUpdateInput: ActiveDirectoryGroupCreateOrUpdateInput.md
    - ActiveDirectoryGroupPage: ActiveDirectoryGroupPage.md
    - AggregationThresholdItem: AggregationThresholdItem.md
    - AiAssistantConversationPage: AiAssistantConversationPage.md
    - AiConversation: AiConversation.md
    - AiMessage: AiMessage.md
    - AiQuestion: AiQuestion.md
    - ApiTokenInfo: ApiTokenInfo.md
    - ApplicationContext: ApplicationContext.md
    - ApplicationContextClassLoader: ApplicationContextClassLoader.md
    - ApplicationContextClassLoaderDefinedPackagesInner: ApplicationContextClassLoaderDefinedPackagesInner.md
    - ApplicationContextClassLoaderParent: ApplicationContextClassLoaderParent.md
    - ApplicationContextClassLoaderParentUnnamedModule: ApplicationContextClassLoaderParentUnnamedModule.md
    - ApplicationContextClassLoaderParentUnnamedModuleClassLoader: ApplicationContextClassLoaderParentUnnamedModuleClassLoader.md
    - ApplicationContextClassLoaderParentUnnamedModuleDescriptor: ApplicationContextClassLoaderParentUnnamedModuleDescriptor.md
    - AsaCompatibilityVersion: AsaCompatibilityVersion.md
    - AsaCompatibleVersion: AsaCompatibleVersion.md
    - AsaCompatibleVersionsResponse: AsaCompatibleVersionsResponse.md
    - AsaConfig: AsaConfig.md
    - AsaCreateOrUpdateInput: AsaCreateOrUpdateInput.md
    - AsaFailoverMate: AsaFailoverMate.md
    - AsaFailoverMode: AsaFailoverMode.md
    - AsaInterface: AsaInterface.md
    - AsaInterfacePage: AsaInterfacePage.md
    - AuditLog: AuditLog.md
    - AuditLogPage: AuditLogPage.md
    - AuthenticationError: AuthenticationError.md
    - Browser: Browser.md
    - BulkOperationAsaDeviceRequest: BulkOperationAsaDeviceRequest.md
    - Cause: Cause.md
    - CdFmcInfo: CdFmcInfo.md
    - CdFmcObject: CdFmcObject.md
    - CdFmcResult: CdFmcResult.md
    - CdoCliMacro: CdoCliMacro.md
    - CdoCliMacroPage: CdoCliMacroPage.md
    - CdoCliResult: CdoCliResult.md
    - CdoCliResultPage: CdoCliResultPage.md
    - CdoRegion: CdoRegion.md
    - CdoRegionList: CdoRegionList.md
    - CdoTokenInfo: CdoTokenInfo.md
    - CdoTransaction: CdoTransaction.md
    - ChangeRequest: ChangeRequest.md
    - ChangeRequestCreateInput: ChangeRequestCreateInput.md
    - ChangeRequestPage: ChangeRequestPage.md
    - Changelog: Changelog.md
    - ChangelogPage: ChangelogPage.md
    - ChassisStatsHealthMetrics: ChassisStatsHealthMetrics.md
    - CliCommandInput: CliCommandInput.md
    - CliMacroCreateInput: CliMacroCreateInput.md
    - CliMacroExecuteInput: CliMacroExecuteInput.md
    - CliMacroPatchInput: CliMacroPatchInput.md
    - ClientDevice: ClientDevice.md
    - ClusterNode: ClusterNode.md
    - Command: Command.md
    - CommandResponse: CommandResponse.md
    - CommonApiError: CommonApiError.md
    - CompatibleDevice: CompatibleDevice.md
    - CompatibleDeviceDto: CompatibleDeviceDto.md
    - CompatibleVersionInfo: CompatibleVersionInfo.md
    - CompatibleVersionInfoDto: CompatibleVersionInfoDto.md
    - CompletionStatusDto: CompletionStatusDto.md
    - ConfigState: ConfigState.md
    - ConflictDetectionInterval: ConflictDetectionInterval.md
    - ConflictDetectionState: ConflictDetectionState.md
    - ConnectivityState: ConnectivityState.md
    - ConnectorType: ConnectorType.md
    - CpuHealthMetrics: CpuHealthMetrics.md
    - CreateRequest: CreateRequest.md
    - Deployed: Deployed.md
    - DestinationDynamicObjectContent: DestinationDynamicObjectContent.md
    - DestinationNetworkContent: DestinationNetworkContent.md
    - DestinationPortContent: DestinationPortContent.md
    - Device: Device.md
    - DeviceEndOfLife: DeviceEndOfLife.md
    - DeviceEndOfLifeDetails: DeviceEndOfLifeDetails.md
    - DeviceEndOfLifeDeviceInfo: DeviceEndOfLifeDeviceInfo.md
    - DeviceEndOfLifeRecommendation: DeviceEndOfLifeRecommendation.md
    - DeviceEndOfLifeReport: DeviceEndOfLifeReport.md
    - DeviceGatewayApiRequest: DeviceGatewayApiRequest.md
    - DeviceLicenseDetail: DeviceLicenseDetail.md
    - DeviceLicenseDto: DeviceLicenseDto.md
    - DeviceLicensePage: DeviceLicensePage.md
    - DeviceMaintenanceWindow: DeviceMaintenanceWindow.md
    - DeviceManagerPatchInput: DeviceManagerPatchInput.md
    - DeviceMetadata: DeviceMetadata.md
    - DevicePage: DevicePage.md
    - DevicePatchInput: DevicePatchInput.md
    - DeviceRole: DeviceRole.md
    - DeviceUpgradeStatusDto: DeviceUpgradeStatusDto.md
    - DevicesPatchInput: DevicesPatchInput.md
    - DiskHealthMetrics: DiskHealthMetrics.md
    - DomainSettings: DomainSettings.md
    - DuoAdminPanelCreateOrUpdateInput: DuoAdminPanelCreateOrUpdateInput.md
    - DuplexType: DuplexType.md
    - DuplicateGroupDto: DuplicateGroupDto.md
    - EnableCdFmcForTenantRequest: EnableCdFmcForTenantRequest.md
    - Entity: Entity.md
    - EntityType: EntityType.md
    - Environment: Environment.md
    - EtherChannelInterfaceCreateInput: EtherChannelInterfaceCreateInput.md
    - EtherChannelInterfacePatchInput: EtherChannelInterfacePatchInput.md
    - Event: Event.md
    - ExportInput: ExportInput.md
    - FilterRegistration: FilterRegistration.md
    - FmcAccessPolicyReference: FmcAccessPolicyReference.md
    - FmcDeviceRecord: FmcDeviceRecord.md
    - FmcHealthMetrics: FmcHealthMetrics.md
    - FmcObjectOverride: FmcObjectOverride.md
    - FmcObjectReference: FmcObjectReference.md
    - FmcRequest: FmcRequest.md
    - FmcTemplateVariable: FmcTemplateVariable.md
    - FtdClusterInfo: FtdClusterInfo.md
    - FtdCompatibilityVersion: FtdCompatibilityVersion.md
    - FtdCreateOrUpdateInput: FtdCreateOrUpdateInput.md
    - FtdDeploymentInput: FtdDeploymentInput.md
    - FtdHaInfo: FtdHaInfo.md
    - FtdMultiDeviceDeploymentInput: FtdMultiDeviceDeploymentInput.md
    - FtdRegistrationInput: FtdRegistrationInput.md
    - FtdUpgradeRunDtoPage: FtdUpgradeRunDtoPage.md
    - FtdVersion: FtdVersion.md
    - FtdVersionsPage: FtdVersionsPage.md
    - FtdVersionsResponse: FtdVersionsResponse.md
    - GlobalSearchResult: GlobalSearchResult.md
    - GroupContent: GroupContent.md
    - HaHealthMetrics: HaHealthMetrics.md
    - HaNode: HaNode.md
    - HttpStatusCode: HttpStatusCode.md
    - Icmp4Value: Icmp4Value.md
    - Icmp6Value: Icmp6Value.md
    - InterfaceErrorSummary: InterfaceErrorSummary.md
    - InterfaceHealthMetrics: InterfaceHealthMetrics.md
    - InterfaceIpAddress: InterfaceIpAddress.md
    - InterfaceIpv4Address: InterfaceIpv4Address.md
    - InterfaceIpv6Address: InterfaceIpv6Address.md
    - InterfaceMetricError: InterfaceMetricError.md
    - InterfaceMetricErrorAggregationResponse: InterfaceMetricErrorAggregationResponse.md
    - InterfaceMode: InterfaceMode.md
    - InterfaceRuntimeData: InterfaceRuntimeData.md
    - InterfaceType: InterfaceType.md
    - Inventory: Inventory.md
    - IosCreateOrUpdateInput: IosCreateOrUpdateInput.md
    - IpType: IpType.md
    - IssuesCount: IssuesCount.md
    - IssuesDto: IssuesDto.md
    - JsonWebKey: JsonWebKey.md
    - JspConfigDescriptor: JspConfigDescriptor.md
    - JspPropertyGroupDescriptor: JspPropertyGroupDescriptor.md
    - JwkSet: JwkSet.md
    - Labels: Labels.md
    - LinkState: LinkState.md
    - ListObjectResponse: ListObjectResponse.md
    - Location: Location.md
    - LogSettings: LogSettings.md
    - ManagedTenantDto: ManagedTenantDto.md
    - MemoryHealthMetrics: MemoryHealthMetrics.md
    - MerakiDeploymentMode: MerakiDeploymentMode.md
    - Meta: Meta.md
    - Metric: Metric.md
    - MetricAggregationItem: MetricAggregationItem.md
    - MetricAggregationListItem: MetricAggregationListItem.md
    - MetricAggregationListResponse: MetricAggregationListResponse.md
    - MetricAggregationResponse: MetricAggregationResponse.md
    - MetricsItem: MetricsItem.md
    - MetricsResponse: MetricsResponse.md
    - MfaEvent: MfaEvent.md
    - MfaEventPage: MfaEventPage.md
    - MspAddTenantInput: MspAddTenantInput.md
    - MspAddUsersToTenantInput: MspAddUsersToTenantInput.md
    - MspAsaCompatibleVersionsDto: MspAsaCompatibleVersionsDto.md
    - MspBulkDeviceUpdateInput: MspBulkDeviceUpdateInput.md
    - MspCalculateCompatibleUpgradeVersionsInput: MspCalculateCompatibleUpgradeVersionsInput.md
    - MspCreateTenantInput: MspCreateTenantInput.md
    - MspDeleteUserGroupsFromTenantInput: MspDeleteUserGroupsFromTenantInput.md
    - MspDeleteUsersFromTenantInput: MspDeleteUsersFromTenantInput.md
    - MspDeviceLicenseDetail: MspDeviceLicenseDetail.md
    - MspDeviceLicenseDto: MspDeviceLicenseDto.md
    - MspDeviceLicensePage: MspDeviceLicensePage.md
    - MspExportInput: MspExportInput.md
    - MspLicenseDto: MspLicenseDto.md
    - MspLicensesPage: MspLicensesPage.md
    - MspManagedCloudService: MspManagedCloudService.md
    - MspManagedCloudServiceDistinctAttributeValues: MspManagedCloudServiceDistinctAttributeValues.md
    - MspManagedCloudServicePage: MspManagedCloudServicePage.md
    - MspManagedDevice: MspManagedDevice.md
    - MspManagedDeviceDistinctAttributeValues: MspManagedDeviceDistinctAttributeValues.md
    - MspManagedDeviceManager: MspManagedDeviceManager.md
    - MspManagedDeviceManagerDistinctAttributeValues: MspManagedDeviceManagerDistinctAttributeValues.md
    - MspManagedDeviceManagersPage: MspManagedDeviceManagersPage.md
    - MspManagedDevicePage: MspManagedDevicePage.md
    - MspManagedTemplate: MspManagedTemplate.md
    - MspManagedTemplateDistinctAttributeValues: MspManagedTemplateDistinctAttributeValues.md
    - MspManagedTemplatesPage: MspManagedTemplatesPage.md
    - MspManagedTenant: MspManagedTenant.md
    - MspManagedTenantDto: MspManagedTenantDto.md
    - MspManagedTenantDtoPage: MspManagedTenantDtoPage.md
    - MspManagedTenantPage: MspManagedTenantPage.md
    - MspSmartAccountDto: MspSmartAccountDto.md
    - MspSmartAccountsPage: MspSmartAccountsPage.md
    - MspUpgradeFtdDevicesInput: MspUpgradeFtdDevicesInput.md
    - MspUpgradeRunDto: MspUpgradeRunDto.md
    - MspUpgradeRunDtoPage: MspUpgradeRunDtoPage.md
    - MspUpgradeRunsAttributeValues: MspUpgradeRunsAttributeValues.md
    - MspVirtualAccountDto: MspVirtualAccountDto.md
    - MspVirtualAccountsPage: MspVirtualAccountsPage.md
    - Network: Network.md
    - NetworkObjectContent: NetworkObjectContent.md
    - OS: OS.md
    - ObjectContent: ObjectContent.md
    - ObjectResponse: ObjectResponse.md
    - OnPremFmcInfo: OnPremFmcInfo.md
    - Override: Override.md
    - Page: Page.md
    - PhysicalInterfacePatchInput: PhysicalInterfacePatchInput.md
    - Policy: Policy.md
    - PortsValue: PortsValue.md
    - ProtocolContent: ProtocolContent.md
    - ProtocolValueContent: ProtocolValueContent.md
    - PublicKey: PublicKey.md
    - RaVpnDeviceInput: RaVpnDeviceInput.md
    - RaVpnSession: RaVpnSession.md
    - RaVpnSessionHealthMetrics: RaVpnSessionHealthMetrics.md
    - RaVpnSessionPage: RaVpnSessionPage.md
    - RedirectView: RedirectView.md
    - ReferenceInfo: ReferenceInfo.md
    - RuleTimeRangeContent: RuleTimeRangeContent.md
    - S2sVpnTunnelHealthMetrics: S2sVpnTunnelHealthMetrics.md
    - Sdc: Sdc.md
    - SdcCreateInput: SdcCreateInput.md
    - SdcPage: SdcPage.md
    - SdcPatchInput: SdcPatchInput.md
    - SecureAccessMetadata: SecureAccessMetadata.md
    - Series: Series.md
    - ServiceObjectContent: ServiceObjectContent.md
    - ServiceObjectValueContent: ServiceObjectValueContent.md
    - ServletContext: ServletContext.md
    - ServletRegistration: ServletRegistration.md
    - SessionCookieConfig: SessionCookieConfig.md
    - SharedObjectValue: SharedObjectValue.md
    - SingleContent: SingleContent.md
    - SmartAccount: SmartAccount.md
    - SmartAccountDto: SmartAccountDto.md
    - SmartAccountsPage: SmartAccountsPage.md
    - SourceDestinationPortsValue: SourceDestinationPortsValue.md
    - SourceDynamicObjectContent: SourceDynamicObjectContent.md
    - SourceNetworkContent: SourceNetworkContent.md
    - SourcePortContent: SourcePortContent.md
    - SpeedType: SpeedType.md
    - SseDeviceData: SseDeviceData.md
    - Staged: Staged.md
    - StateMachineDetails: StateMachineDetails.md
    - StateMachineError: StateMachineError.md
    - Status: Status.md
    - StatusInfo: StatusInfo.md
    - SubInterfaceCreateInput: SubInterfaceCreateInput.md
    - SubInterfacePatchInput: SubInterfacePatchInput.md
    - Summary: Summary.md
    - SwitchPortConfig: SwitchPortConfig.md
    - TaglibDescriptor: TaglibDescriptor.md
    - Target: Target.md
    - TargetsRequest: TargetsRequest.md
    - Tenant: Tenant.md
    - TenantPage: TenantPage.md
    - TenantSettings: TenantSettings.md
    - UnifiedObjectListView: UnifiedObjectListView.md
    - UniversalZtnaSettings: UniversalZtnaSettings.md
    - UpdateRequest: UpdateRequest.md
    - UpgradeAsaDeviceInput: UpgradeAsaDeviceInput.md
    - UpgradeAsaDevicesInput: UpgradeAsaDevicesInput.md
    - UpgradeCompatibilityInfoDto: UpgradeCompatibilityInfoDto.md
    - UpgradeFtdDeviceInput: UpgradeFtdDeviceInput.md
    - UpgradeFtdDevicesInput: UpgradeFtdDevicesInput.md
    - UpgradeRunDto: UpgradeRunDto.md
    - UpgradeRunMetadataDto: UpgradeRunMetadataDto.md
    - UpgradeRunModifyInput: UpgradeRunModifyInput.md
    - UrlObjectContent: UrlObjectContent.md
    - User: User.md
    - UserCreateOrUpdateInput: UserCreateOrUpdateInput.md
    - UserInput: UserInput.md
    - UserPage: UserPage.md
    - UserRole: UserRole.md
    - VirtualAccountDto: VirtualAccountDto.md
    - VirtualAccountsPage: VirtualAccountsPage.md
    - VlanIdRange: VlanIdRange.md
    - VlanInterfaceCreateInput: VlanInterfaceCreateInput.md
    - VlanInterfacePatchInput: VlanInterfacePatchInput.md
    - VpnHealthMetrics: VpnHealthMetrics.md
    - ZtpOnboardingInput: ZtpOnboardingInput.md
    - ZtpOnboardingTemplateConfiguration: ZtpOnboardingTemplateConfiguration.md
